---
jupyter:
  kernelspec:
    display_name: R
    language: R
    name: ir
  language_info:
    codemirror_mode: r
    file_extension: .r
    mimetype: text/x-r-source
    name: R
    pygments_lexer: r
    version: 4.2.1
  nbformat: 4
  nbformat_minor: 5
---

::: {.cell .code execution_count="1" scrolled="true"}
``` {.R}
my_packages <- c("tidyverse", "lme4", "nlme", "readxl", "lmerTest", "dplyr")
```
:::

::: {.cell .code execution_count="3" scrolled="true"}
``` {.R}
lapply(my_packages, require, character.only = TRUE)
```

::: {.output .stream .stderr}
    Loading required package: tidyverse

    ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ✔ tidyr   1.2.1      ✔ stringr 1.4.1 
    ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ✖ dplyr::filter() masks stats::filter()
    ✖ dplyr::lag()    masks stats::lag()
    Loading required package: lme4

    Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
    “there is no package called ‘lme4’”
    Loading required package: nlme


    Attaching package: ‘nlme’


    The following object is masked from ‘package:dplyr’:

        collapse


    Loading required package: readxl

    Loading required package: lmerTest

    Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
    “there is no package called ‘lmerTest’”
:::

::: {.output .display_data}
```{=html}
<ol>
	<li>TRUE</li>
	<li>FALSE</li>
	<li>TRUE</li>
	<li>TRUE</li>
	<li>FALSE</li>
	<li>TRUE</li>
</ol>
```
:::
:::

::: {.cell .code execution_count="6"}
``` {.R}
# This is the start of cleaning and tidying process
```
:::

::: {.cell .code execution_count="7"}
``` {.R}
#List excel sheets
combined_data <- excel_sheets("2_People_untidy_MD.xlsx") %>% map_df(~read_xlsx("2_People_untidy_MD.xlsx",.))
head(combined_data)
```

::: {.output .display_data}
```{=html}
<table class="dataframe">
<caption>A tibble: 6 × 5</caption>
<thead>
	<tr><th scope=col>Moon</th><th scope=col>People_total</th><th scope=col>msq</th><th scope=col>Date</th><th scope=col>Time</th></tr>
	<tr><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th></tr>
</thead>
<tbody>
	<tr><td>Muku</td><td>NA</td><td>8059.53</td><td>20220628</td><td>0</td></tr>
	<tr><td>Muku</td><td>NA</td><td>8059.53</td><td>20220628</td><td>0</td></tr>
	<tr><td>Muku</td><td>NA</td><td>8059.53</td><td>20220628</td><td>0</td></tr>
	<tr><td>Muku</td><td>NA</td><td>8059.53</td><td>20220628</td><td>4</td></tr>
	<tr><td>Muku</td><td>NA</td><td>8059.53</td><td>20220628</td><td>4</td></tr>
	<tr><td>Muku</td><td>NA</td><td>8059.53</td><td>20220628</td><td>4</td></tr>
</tbody>
</table>
```
:::
:::

::: {.cell .code execution_count="8"}
``` {.R}
#Replace missing values with 0
combined_data[is.na(combined_data)] <- 0
```
:::

::: {.cell .code execution_count="9"}
``` {.R}
# Divide People_total / msq to get total ppl_msq
combined_data$ppl_msq <- (combined_data$People_total / combined_data$msq)
```
:::

::: {.cell .code execution_count="10"}
``` {.R}
#preview
head(combined_data)
tail(combined_data)
```

::: {.output .display_data}
```{=html}
<table class="dataframe">
<caption>A tibble: 6 × 6</caption>
<thead>
	<tr><th scope=col>Moon</th><th scope=col>People_total</th><th scope=col>msq</th><th scope=col>Date</th><th scope=col>Time</th><th scope=col>ppl_msq</th></tr>
	<tr><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th></tr>
</thead>
<tbody>
	<tr><td>Muku</td><td>0</td><td>8059.53</td><td>20220628</td><td>0</td><td>0</td></tr>
	<tr><td>Muku</td><td>0</td><td>8059.53</td><td>20220628</td><td>0</td><td>0</td></tr>
	<tr><td>Muku</td><td>0</td><td>8059.53</td><td>20220628</td><td>0</td><td>0</td></tr>
	<tr><td>Muku</td><td>0</td><td>8059.53</td><td>20220628</td><td>4</td><td>0</td></tr>
	<tr><td>Muku</td><td>0</td><td>8059.53</td><td>20220628</td><td>4</td><td>0</td></tr>
	<tr><td>Muku</td><td>0</td><td>8059.53</td><td>20220628</td><td>4</td><td>0</td></tr>
</tbody>
</table>
```
:::

::: {.output .display_data}
```{=html}
<table class="dataframe">
<caption>A tibble: 6 × 6</caption>
<thead>
	<tr><th scope=col>Moon</th><th scope=col>People_total</th><th scope=col>msq</th><th scope=col>Date</th><th scope=col>Time</th><th scope=col>ppl_msq</th></tr>
	<tr><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th></tr>
</thead>
<tbody>
	<tr><td>Hoku</td><td>4</td><td>8059.53</td><td>20220713</td><td>20</td><td>0.0004963069</td></tr>
	<tr><td>Hoku</td><td>4</td><td>8059.53</td><td>20220713</td><td>20</td><td>0.0004963069</td></tr>
	<tr><td>Hoku</td><td>4</td><td>8059.53</td><td>20220713</td><td>20</td><td>0.0004963069</td></tr>
	<tr><td>Hoku</td><td>0</td><td>8059.53</td><td>20220713</td><td>24</td><td>0.0000000000</td></tr>
	<tr><td>Hoku</td><td>0</td><td>8059.53</td><td>20220713</td><td>24</td><td>0.0000000000</td></tr>
	<tr><td>Hoku</td><td>0</td><td>8059.53</td><td>20220713</td><td>24</td><td>0.0000000000</td></tr>
</tbody>
</table>
```
:::
:::

::: {.cell .code execution_count="11"}
``` {.R}
#all BP3 and OC concentration ([UVF]) data from individual CSV files; str preview showing NA values
conc_muku <- data.frame(read.csv("conc_muku.csv"))
conc_ole <- data.frame(read.csv("conc_ole.csv"))
conc_hoku <- data.frame(read.csv("conc_hoku.csv"))
str(conc_muku)
str(conc_ole)
str(conc_hoku)
```

::: {.output .stream .stdout}
    'data.frame':	30 obs. of  4 variables:
     $ Moon: chr  "Muku" "Muku" "Muku" "Muku" ...
     $ Time: int  0 0 0 4 4 4 8 8 8 9 ...
     $ BP3 : num  12.3 13.9 11.1 20 20.1 ...
     $ OC  : num  NA NA NA NA NA ...
    'data.frame':	30 obs. of  4 variables:
     $ Moon: chr  "ʻOlekūkolu" "ʻOlekūkolu" "ʻOlekūkolu" "ʻOlekūkolu" ...
     $ Time: int  0 0 0 4 4 4 8 8 8 9 ...
     $ BP3 : num  21.2 21.5 19.3 20.3 21.7 ...
     $ OC  : num  NA NA NA 15.6 12.8 ...
    'data.frame':	30 obs. of  4 variables:
     $ Moon: chr  "Hoku" "Hoku" "Hoku" "Hoku" ...
     $ Time: int  0 0 0 4 4 4 8 8 8 9 ...
     $ BP3 : num  36.9 35.1 35.9 36.6 37.1 ...
     $ OC  : num  87.4 73.7 71 84.2 109.1 ...
:::
:::

::: {.cell .code execution_count="12"}
``` {.R}
#combine all [UVF] data to one data frame
conc <- rbind(conc_muku, conc_ole, conc_hoku)
```
:::

::: {.cell .code execution_count="13"}
``` {.R}
#replace NA values with 0; str preview
conc[is.na(conc)] <- 0
str(conc)
```

::: {.output .stream .stdout}
    'data.frame':	90 obs. of  4 variables:
     $ Moon: chr  "Muku" "Muku" "Muku" "Muku" ...
     $ Time: int  0 0 0 4 4 4 8 8 8 9 ...
     $ BP3 : num  12.3 13.9 11.1 20 20.1 ...
     $ OC  : num  0 0 0 0 0 ...
:::
:::

::: {.cell .code execution_count="14"}
``` {.R}
#combine [UVF] and pple from combined_data; head preview
conc_pple <- cbind(conc,combined_data)
head(conc_pple)
```

::: {.output .display_data}
```{=html}
<table class="dataframe">
<caption>A data.frame: 6 × 10</caption>
<thead>
	<tr><th></th><th scope=col>Moon</th><th scope=col>Time</th><th scope=col>BP3</th><th scope=col>OC</th><th scope=col>Moon</th><th scope=col>People_total</th><th scope=col>msq</th><th scope=col>Date</th><th scope=col>Time</th><th scope=col>ppl_msq</th></tr>
	<tr><th></th><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th></tr>
</thead>
<tbody>
	<tr><th scope=row>1</th><td>Muku</td><td>0</td><td>12.34324</td><td>0</td><td>Muku</td><td>0</td><td>8059.53</td><td>20220628</td><td>0</td><td>0</td></tr>
	<tr><th scope=row>2</th><td>Muku</td><td>0</td><td>13.92103</td><td>0</td><td>Muku</td><td>0</td><td>8059.53</td><td>20220628</td><td>0</td><td>0</td></tr>
	<tr><th scope=row>3</th><td>Muku</td><td>0</td><td>11.11400</td><td>0</td><td>Muku</td><td>0</td><td>8059.53</td><td>20220628</td><td>0</td><td>0</td></tr>
	<tr><th scope=row>4</th><td>Muku</td><td>4</td><td>20.03424</td><td>0</td><td>Muku</td><td>0</td><td>8059.53</td><td>20220628</td><td>4</td><td>0</td></tr>
	<tr><th scope=row>5</th><td>Muku</td><td>4</td><td>20.05967</td><td>0</td><td>Muku</td><td>0</td><td>8059.53</td><td>20220628</td><td>4</td><td>0</td></tr>
	<tr><th scope=row>6</th><td>Muku</td><td>4</td><td>18.89155</td><td>0</td><td>Muku</td><td>0</td><td>8059.53</td><td>20220628</td><td>4</td><td>0</td></tr>
</tbody>
</table>
```
:::
:::

::: {.cell .code execution_count="15"}
``` {.R}
#remove duplicate columns, reorganize columns; head preview
conc_pple_2 <- conc_pple[,-5]
conc_pple_3 <- conc_pple_2[,-8]
conc_pple_4 <- conc_pple_3[,-6]
conc_pple_fin <- conc_pple_4 %>% relocate(Date, .after = Moon)
head(conc_pple_fin)
```

::: {.output .display_data}
```{=html}
<table class="dataframe">
<caption>A data.frame: 6 × 7</caption>
<thead>
	<tr><th></th><th scope=col>Moon</th><th scope=col>Date</th><th scope=col>Time</th><th scope=col>BP3</th><th scope=col>OC</th><th scope=col>People_total</th><th scope=col>ppl_msq</th></tr>
	<tr><th></th><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th></tr>
</thead>
<tbody>
	<tr><th scope=row>1</th><td>Muku</td><td>20220628</td><td>0</td><td>12.34324</td><td>0</td><td>0</td><td>0</td></tr>
	<tr><th scope=row>2</th><td>Muku</td><td>20220628</td><td>0</td><td>13.92103</td><td>0</td><td>0</td><td>0</td></tr>
	<tr><th scope=row>3</th><td>Muku</td><td>20220628</td><td>0</td><td>11.11400</td><td>0</td><td>0</td><td>0</td></tr>
	<tr><th scope=row>4</th><td>Muku</td><td>20220628</td><td>4</td><td>20.03424</td><td>0</td><td>0</td><td>0</td></tr>
	<tr><th scope=row>5</th><td>Muku</td><td>20220628</td><td>4</td><td>20.05967</td><td>0</td><td>0</td><td>0</td></tr>
	<tr><th scope=row>6</th><td>Muku</td><td>20220628</td><td>4</td><td>18.89155</td><td>0</td><td>0</td><td>0</td></tr>
</tbody>
</table>
```
:::
:::

::: {.cell .code execution_count="16"}
``` {.R}
### Kaimana_tide dataset
Diamond_data <- read.csv("Diamond_tide.csv")
str(Diamond_data)
```

::: {.output .stream .stdout}
    'data.frame':	90 obs. of  6 variables:
     $ Date    : int  20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 ...
     $ Moon    : chr  "Muku" "Muku" "Muku" "Muku" ...
     $ Time    : num  0 0 0 4 4 4 8 8 8 9 ...
     $ Tide    : num  0.271 0.271 0.271 0.505 0.505 ...
     $ PreTide : num  0.24 0.24 0.24 0.54 0.54 0.54 0.54 0.54 0.54 -0.15 ...
     $ PostTide: num  0.54 0.54 0.54 -0.15 -0.15 -0.15 -0.15 -0.15 -0.15 2.28 ...
:::
:::

::: {.cell .code execution_count="17"}
``` {.R}
### Combining PreTide and PostTide columns into one
Diamond_data$PreTide_PostTide <- paste(Diamond_data$PreTide, Diamond_data$PostTide, sep="_")
str(Diamond_data)
```

::: {.output .stream .stdout}
    'data.frame':	90 obs. of  7 variables:
     $ Date            : int  20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 ...
     $ Moon            : chr  "Muku" "Muku" "Muku" "Muku" ...
     $ Time            : num  0 0 0 4 4 4 8 8 8 9 ...
     $ Tide            : num  0.271 0.271 0.271 0.505 0.505 ...
     $ PreTide         : num  0.24 0.24 0.24 0.54 0.54 0.54 0.54 0.54 0.54 -0.15 ...
     $ PostTide        : num  0.54 0.54 0.54 -0.15 -0.15 -0.15 -0.15 -0.15 -0.15 2.28 ...
     $ PreTide_PostTide: chr  "0.24_0.54" "0.24_0.54" "0.24_0.54" "0.54_-0.15" ...
:::
:::

::: {.cell .code execution_count="18"}
``` {.R}
### Removing old columns
##download this one as csv
tide <- Diamond_data[c("Date", "Moon", "Time", "Tide", "PreTide_PostTide")]
str(tide)
```

::: {.output .stream .stdout}
    'data.frame':	90 obs. of  5 variables:
     $ Date            : int  20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 ...
     $ Moon            : chr  "Muku" "Muku" "Muku" "Muku" ...
     $ Time            : num  0 0 0 4 4 4 8 8 8 9 ...
     $ Tide            : num  0.271 0.271 0.271 0.505 0.505 ...
     $ PreTide_PostTide: chr  "0.24_0.54" "0.24_0.54" "0.24_0.54" "0.54_-0.15" ...
:::
:::

::: {.cell .code execution_count="19"}
``` {.R}
### Tidying up the data again (Cleaning)
tide[c('PreTide', 'PostTide')] <- str_split_fixed(tide$PreTide_PostTide, '_', 2)
str(tide)
```

::: {.output .stream .stdout}
    'data.frame':	90 obs. of  7 variables:
     $ Date            : int  20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 ...
     $ Moon            : chr  "Muku" "Muku" "Muku" "Muku" ...
     $ Time            : num  0 0 0 4 4 4 8 8 8 9 ...
     $ Tide            : num  0.271 0.271 0.271 0.505 0.505 ...
     $ PreTide_PostTide: chr  "0.24_0.54" "0.24_0.54" "0.24_0.54" "0.54_-0.15" ...
     $ PreTide         : chr  "0.24" "0.24" "0.24" "0.54" ...
     $ PostTide        : chr  "0.54" "0.54" "0.54" "-0.15" ...
:::
:::

::: {.cell .code execution_count="20"}
``` {.R}
### Removing extra joint column (Cleaning)
tide_2 <- tide[c("Date", "Moon", "Time", "Tide", "PreTide", "PostTide")]
str(tide_2)
```

::: {.output .stream .stdout}
    'data.frame':	90 obs. of  6 variables:
     $ Date    : int  20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 ...
     $ Moon    : chr  "Muku" "Muku" "Muku" "Muku" ...
     $ Time    : num  0 0 0 4 4 4 8 8 8 9 ...
     $ Tide    : num  0.271 0.271 0.271 0.505 0.505 ...
     $ PreTide : chr  "0.24" "0.24" "0.24" "0.54" ...
     $ PostTide: chr  "0.54" "0.54" "0.54" "-0.15" ...
:::
:::

::: {.cell .code execution_count="21"}
``` {.R}
### Convert Tide column from inches to meters
tide_2$Tide <- tide_2$Tide * 0.3048
str(tide_2)
```

::: {.output .stream .stdout}
    'data.frame':	90 obs. of  6 variables:
     $ Date    : int  20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 ...
     $ Moon    : chr  "Muku" "Muku" "Muku" "Muku" ...
     $ Time    : num  0 0 0 4 4 4 8 8 8 9 ...
     $ Tide    : num  0.0826 0.0826 0.0826 0.1541 0.1541 ...
     $ PreTide : chr  "0.24" "0.24" "0.24" "0.54" ...
     $ PostTide: chr  "0.54" "0.54" "0.54" "-0.15" ...
:::
:::

::: {.cell .code execution_count="22"}
``` {.R}
### Changing PreTide and PostTide columns from character to double strings
tide_2$PreTide = as.double(tide_2$PreTide)
tide_2$PostTide = as.double(tide_2$PostTide)
str(tide_2)
```

::: {.output .stream .stdout}
    'data.frame':	90 obs. of  6 variables:
     $ Date    : int  20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 ...
     $ Moon    : chr  "Muku" "Muku" "Muku" "Muku" ...
     $ Time    : num  0 0 0 4 4 4 8 8 8 9 ...
     $ Tide    : num  0.0826 0.0826 0.0826 0.1541 0.1541 ...
     $ PreTide : num  0.24 0.24 0.24 0.54 0.54 0.54 0.54 0.54 0.54 -0.15 ...
     $ PostTide: num  0.54 0.54 0.54 -0.15 -0.15 -0.15 -0.15 -0.15 -0.15 2.28 ...
:::
:::

::: {.cell .code execution_count="23"}
``` {.R}
### Convert PreTide and PostTide columns from inches to meters
tide_2$PreTide <- tide_2$PreTide * 0.3048
tide_2$PostTide <- tide_2$PostTide * 0.3048
str(tide_2)
```

::: {.output .stream .stdout}
    'data.frame':	90 obs. of  6 variables:
     $ Date    : int  20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 20220628 ...
     $ Moon    : chr  "Muku" "Muku" "Muku" "Muku" ...
     $ Time    : num  0 0 0 4 4 4 8 8 8 9 ...
     $ Tide    : num  0.0826 0.0826 0.0826 0.1541 0.1541 ...
     $ PreTide : num  0.0732 0.0732 0.0732 0.1646 0.1646 ...
     $ PostTide: num  0.1646 0.1646 0.1646 -0.0457 -0.0457 ...
:::
:::

::: {.cell .code execution_count="24"}
``` {.R}
#combine [UVF] and pple data with tidal data from tide_2
Diamond_all <- cbind(conc_pple_fin,tide_2)
head(Diamond_all)
```

::: {.output .display_data}
```{=html}
<table class="dataframe">
<caption>A data.frame: 6 × 13</caption>
<thead>
	<tr><th></th><th scope=col>Moon</th><th scope=col>Date</th><th scope=col>Time</th><th scope=col>BP3</th><th scope=col>OC</th><th scope=col>People_total</th><th scope=col>ppl_msq</th><th scope=col>Date</th><th scope=col>Moon</th><th scope=col>Time</th><th scope=col>Tide</th><th scope=col>PreTide</th><th scope=col>PostTide</th></tr>
	<tr><th></th><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th></tr>
</thead>
<tbody>
	<tr><th scope=row>1</th><td>Muku</td><td>20220628</td><td>0</td><td>12.34324</td><td>0</td><td>0</td><td>0</td><td>20220628</td><td>Muku</td><td>0</td><td>0.08264164</td><td>0.073152</td><td> 0.164592</td></tr>
	<tr><th scope=row>2</th><td>Muku</td><td>20220628</td><td>0</td><td>13.92103</td><td>0</td><td>0</td><td>0</td><td>20220628</td><td>Muku</td><td>0</td><td>0.08264164</td><td>0.073152</td><td> 0.164592</td></tr>
	<tr><th scope=row>3</th><td>Muku</td><td>20220628</td><td>0</td><td>11.11400</td><td>0</td><td>0</td><td>0</td><td>20220628</td><td>Muku</td><td>0</td><td>0.08264164</td><td>0.073152</td><td> 0.164592</td></tr>
	<tr><th scope=row>4</th><td>Muku</td><td>20220628</td><td>4</td><td>20.03424</td><td>0</td><td>0</td><td>0</td><td>20220628</td><td>Muku</td><td>4</td><td>0.15407579</td><td>0.164592</td><td>-0.045720</td></tr>
	<tr><th scope=row>5</th><td>Muku</td><td>20220628</td><td>4</td><td>20.05967</td><td>0</td><td>0</td><td>0</td><td>20220628</td><td>Muku</td><td>4</td><td>0.15407579</td><td>0.164592</td><td>-0.045720</td></tr>
	<tr><th scope=row>6</th><td>Muku</td><td>20220628</td><td>4</td><td>18.89155</td><td>0</td><td>0</td><td>0</td><td>20220628</td><td>Muku</td><td>4</td><td>0.15407579</td><td>0.164592</td><td>-0.045720</td></tr>
</tbody>
</table>
```
:::
:::

::: {.cell .code execution_count="25" scrolled="false"}
``` {.R}
#remove duplicate columns
Diamond_all_1 <- Diamond_all[,-10]
Diamond_all_2 <- Diamond_all_1[,-9]
Diamond_all_fin <- Diamond_all_2[,-8]
```
:::

::: {.cell .code execution_count="26"}
``` {.R}
head(Diamond_all_fin)
str(Diamond_all_fin)
```

::: {.output .display_data}
```{=html}
<table class="dataframe">
<caption>A data.frame: 6 × 10</caption>
<thead>
	<tr><th></th><th scope=col>Moon</th><th scope=col>Date</th><th scope=col>Time</th><th scope=col>BP3</th><th scope=col>OC</th><th scope=col>People_total</th><th scope=col>ppl_msq</th><th scope=col>Tide</th><th scope=col>PreTide</th><th scope=col>PostTide</th></tr>
	<tr><th></th><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th><th scope=col>&lt;dbl&gt;</th></tr>
</thead>
<tbody>
	<tr><th scope=row>1</th><td>Muku</td><td>20220628</td><td>0</td><td>12.34324</td><td>0</td><td>0</td><td>0</td><td>0.08264164</td><td>0.073152</td><td> 0.164592</td></tr>
	<tr><th scope=row>2</th><td>Muku</td><td>20220628</td><td>0</td><td>13.92103</td><td>0</td><td>0</td><td>0</td><td>0.08264164</td><td>0.073152</td><td> 0.164592</td></tr>
	<tr><th scope=row>3</th><td>Muku</td><td>20220628</td><td>0</td><td>11.11400</td><td>0</td><td>0</td><td>0</td><td>0.08264164</td><td>0.073152</td><td> 0.164592</td></tr>
	<tr><th scope=row>4</th><td>Muku</td><td>20220628</td><td>4</td><td>20.03424</td><td>0</td><td>0</td><td>0</td><td>0.15407579</td><td>0.164592</td><td>-0.045720</td></tr>
	<tr><th scope=row>5</th><td>Muku</td><td>20220628</td><td>4</td><td>20.05967</td><td>0</td><td>0</td><td>0</td><td>0.15407579</td><td>0.164592</td><td>-0.045720</td></tr>
	<tr><th scope=row>6</th><td>Muku</td><td>20220628</td><td>4</td><td>18.89155</td><td>0</td><td>0</td><td>0</td><td>0.15407579</td><td>0.164592</td><td>-0.045720</td></tr>
</tbody>
</table>
```
:::

::: {.output .stream .stdout}
    'data.frame':	90 obs. of  10 variables:
     $ Moon        : chr  "Muku" "Muku" "Muku" "Muku" ...
     $ Date        : num  20220628 20220628 20220628 20220628 20220628 ...
     $ Time        : int  0 0 0 4 4 4 8 8 8 9 ...
     $ BP3         : num  12.3 13.9 11.1 20 20.1 ...
     $ OC          : num  0 0 0 0 0 ...
     $ People_total: num  0 0 0 0 0 0 9 9 9 11 ...
     $ ppl_msq     : num  0 0 0 0 0 ...
     $ Tide        : num  0.0826 0.0826 0.0826 0.1541 0.1541 ...
     $ PreTide     : num  0.0732 0.0732 0.0732 0.1646 0.1646 ...
     $ PostTide    : num  0.1646 0.1646 0.1646 -0.0457 -0.0457 ...
:::
:::

::: {.cell .code execution_count="27"}
``` {.R}
#Export tidy csv file
write.csv(Diamond_all_fin, "DiamondBeach_all.csv")
```
:::

::: {.cell .code execution_count="28"}
``` {.R}
#This is the start of mixed model creation
```
:::

::: {.cell .code execution_count="29"}
``` {.R}
Diamond_all_fin$ppl_msq_s <- scale(Diamond_all_fin$ppl_msq) 
```
:::

::: {.cell .code execution_count="30"}
``` {.R}
Diamond_all_fin$Time_s <- scale(Diamond_all_fin$Time) 
```
:::

::: {.cell .code execution_count="31"}
``` {.R}
Diamond_all_fin$Tide_s <- scale(Diamond_all_fin$Tide) 
```
:::

::: {.cell .code execution_count="32"}
``` {.R}
Diamond_all_fin$Time <- as.numeric(Diamond_all_fin$Time)
```
:::

::: {.cell .code execution_count="33"}
``` {.R}
Diamond_all_fin = Diamond_all_fin %>%
mutate(Moon_s = recode(Diamond_all_fin$Moon, 
                      "Muku" = 1, 
                      "Hoku" = 2, 
                      "ʻOlekūkolu" = 3))
```
:::

::: {.cell .code execution_count="34"}
``` {.R}
#Time of day effect on people m^2 
#P value shows effect on ppl_msq from time is significant
T_o_D_ppl_msq <- lm(ppl_msq_s ~ Time_s, data = Diamond_all_fin)
summary(T_o_D_ppl_msq)
```

::: {.output .display_data}

    Call:
    lm(formula = ppl_msq_s ~ Time_s, data = Diamond_all_fin)

    Residuals:
        Min      1Q  Median      3Q     Max 
    -1.3323 -0.7431 -0.2025  0.8924  1.6842 

    Coefficients:
                 Estimate Std. Error t value Pr(>|t|)  
    (Intercept) 2.965e-17  1.037e-01   0.000   1.0000  
    Time_s      2.075e-01  1.043e-01   1.989   0.0498 *
    ---
    Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

    Residual standard error: 0.9838 on 88 degrees of freedom
    Multiple R-squared:  0.04304,	Adjusted R-squared:  0.03216 
    F-statistic: 3.958 on 1 and 88 DF,  p-value: 0.04977
:::
:::

::: {.cell .code execution_count="35"}
``` {.R}
# Concentration of OC by time of day and ppl_msq
Time.vs.OC <- lmer(OC ~ Time_s + ppl_msq_s + (1|Moon_s), data = Diamond_all_fin)
summary(Time.vs.OC)
```

::: {.output .error ename="ERROR" evalue="Error in lmer(OC ~ Time_s + ppl_msq_s + (1 | Moon_s), data = Diamond_all_fin): could not find function \"lmer\"
"}
    Error in lmer(OC ~ Time_s + ppl_msq_s + (1 | Moon_s), data = Diamond_all_fin): could not find function "lmer"
    Traceback:
:::
:::

::: {.cell .code execution_count="36"}
``` {.R}
# Concentration of BP3 by time of day and ppl_msq
Time.vs.BP3 <- lmer(BP3 ~ Time_s + ppl_msq_s + (1|Moon_s), data = Diamond_all_fin)
summary(Time.vs.BP3)
```

::: {.output .error ename="ERROR" evalue="Error in lmer(BP3 ~ Time_s + ppl_msq_s + (1 | Moon_s), data = Diamond_all_fin): could not find function \"lmer\"
"}
    Error in lmer(BP3 ~ Time_s + ppl_msq_s + (1 | Moon_s), data = Diamond_all_fin): could not find function "lmer"
    Traceback:
:::
:::

::: {.cell .code execution_count="37"}
``` {.R}
# Concentration of BP3 off tide, time, and ppl_msq
Tide.vs.BP3 <- lmer(BP3 ~ Tide_s + Time_s + ppl_msq_s + (1|Moon_s), data = Diamond_all_fin)
summary(Tide.vs.BP3)
```

::: {.output .error ename="ERROR" evalue="Error in lmer(BP3 ~ Tide_s + Time_s + ppl_msq_s + (1 | Moon_s), data = Diamond_all_fin): could not find function \"lmer\"
"}
    Error in lmer(BP3 ~ Tide_s + Time_s + ppl_msq_s + (1 | Moon_s), data = Diamond_all_fin): could not find function "lmer"
    Traceback:
:::
:::

::: {.cell .code execution_count="38"}
``` {.R}
# Concentration of OC off tide, time, and ppl_msq
Tide.vs.OC <- lmer(OC ~ Tide_s + Time_s + ppl_msq_s + (1|Moon_s), data = Diamond_all_fin)
summary(Tide.vs.OC)
```

::: {.output .error ename="ERROR" evalue="Error in lmer(OC ~ Tide_s + Time_s + ppl_msq_s + (1 | Moon_s), data = Diamond_all_fin): could not find function \"lmer\"
"}
    Error in lmer(OC ~ Tide_s + Time_s + ppl_msq_s + (1 | Moon_s), data = Diamond_all_fin): could not find function "lmer"
    Traceback:
:::
:::

::: {.cell .code execution_count="39"}
``` {.R}
# Concentration of OC versus ppl_msq and time
PPL.vs.OC <- lmer(OC ~ ppl_msq + Time_s + (1|Moon_s), data = Diamond_all_fin)
summary(PPL.vs.OC)
```

::: {.output .error ename="ERROR" evalue="Error in lmer(OC ~ ppl_msq + Time_s + (1 | Moon_s), data = Diamond_all_fin): could not find function \"lmer\"
"}
    Error in lmer(OC ~ ppl_msq + Time_s + (1 | Moon_s), data = Diamond_all_fin): could not find function "lmer"
    Traceback:
:::
:::

::: {.cell .code execution_count="51"}
``` {.R}
# Concentration of BP3 versus ppl_msq and time
PPL.vs.BP3 <- lmer(BP3 ~ ppl_msq + Time_s + (1|Moon_s), data = Diamond_all_fin)
summary(PPL.vs.BP3)
```

::: {.output .error ename="ERROR" evalue="Error in lmer(BP3 ~ ppl_msq + Time_s + (1 | Moon_s), data = Diamond_all_fin): could not find function \"lmer\"
"}
    Error in lmer(BP3 ~ ppl_msq + Time_s + (1 | Moon_s), data = Diamond_all_fin): could not find function "lmer"
    Traceback:
:::
:::

::: {.cell .code execution_count="41"}
``` {.R}
##BP3: effect of pretide(w/ time of day interaction) 
##and posttide (with tide of day interaction) on [BP3].
names(Diamond_all_fin)
```

::: {.output .display_data}
```{=html}
<style>
.list-inline {list-style: none; margin:0; padding: 0}
.list-inline>li {display: inline-block}
.list-inline>li:not(:last-child)::after {content: "\00b7"; padding: 0 .5ex}
</style>
<ol class=list-inline><li>'Moon'</li><li>'Date'</li><li>'Time'</li><li>'BP3'</li><li>'OC'</li><li>'People_total'</li><li>'ppl_msq'</li><li>'Tide'</li><li>'PreTide'</li><li>'PostTide'</li><li>'ppl_msq_s'</li><li>'Time_s'</li><li>'Tide_s'</li><li>'Moon_s'</li></ol>
```
:::
:::

::: {.cell .code execution_count="50"}
``` {.R}
BP3_pre_post <- lmer(BP3 ~ PreTide*Time_s + PostTide*Time_s + (1|Moon_s), data = Diamond_all_fin)
summary(BP3_pre_post)
```

::: {.output .error ename="ERROR" evalue="Error in lmer(BP3 ~ PreTide * Time_s + PostTide * Time_s + (1 | Moon_s), : could not find function \"lmer\"
"}
    Error in lmer(BP3 ~ PreTide * Time_s + PostTide * Time_s + (1 | Moon_s), : could not find function "lmer"
    Traceback:
:::
:::

::: {.cell .code}
``` {.R}
```
:::
